// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: controller.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cookie represents a single HTTP cookie that a worker has obtained after
// solving a JS/bot-detection challenge.
type Cookie struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Domain string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path   string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Unix timestamp (seconds).  Zero means session cookie (no explicit expiry).
	ExpiresUnix   int64 `protobuf:"varint,5,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	Secure        bool  `protobuf:"varint,6,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool  `protobuf:"varint,7,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *Cookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Cookie) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *Cookie) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Cookie) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

// SessionStatus describes the current lifecycle state of one session.
type SessionStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique session identifier (0-1999 for a 2 000-session cluster).
	SessionId int32 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Identifier of the PC / node that owns this session, e.g. "pc-1".
	PcId string `protobuf:"bytes,2,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	// Lifecycle state: "idle" | "active" | "challenge" | "closed".
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// Last-known cookie value for this session (empty when not authenticated).
	CookieValue   string `protobuf:"bytes,4,opt,name=cookie_value,json=cookieValue,proto3" json:"cookie_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatus) Reset() {
	*x = SessionStatus{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatus) ProtoMessage() {}

func (x *SessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatus.ProtoReflect.Descriptor instead.
func (*SessionStatus) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStatus) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionStatus) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *SessionStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionStatus) GetCookieValue() string {
	if x != nil {
		return x.CookieValue
	}
	return ""
}

// BroadcastCookieRequest is sent by the worker that solved a challenge.
// The master stores the cookies in the Global Cookie Jar and fans them out
// to every subscribed worker via the WatchCookies stream.
type BroadcastCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	SessionId     int32                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cookies       []*Cookie              `protobuf:"bytes,3,rep,name=cookies,proto3" json:"cookies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastCookieRequest) Reset() {
	*x = BroadcastCookieRequest{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastCookieRequest) ProtoMessage() {}

func (x *BroadcastCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastCookieRequest.ProtoReflect.Descriptor instead.
func (*BroadcastCookieRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastCookieRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *BroadcastCookieRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *BroadcastCookieRequest) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type BroadcastCookieResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true when the master accepted and stored the cookies.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastCookieResponse) Reset() {
	*x = BroadcastCookieResponse{}
	mi := &file_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastCookieResponse) ProtoMessage() {}

func (x *BroadcastCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastCookieResponse.ProtoReflect.Descriptor instead.
func (*BroadcastCookieResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastCookieResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// UpdateStatusRequest lets a worker report a session's current state.
type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *SessionStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusRequest) GetStatus() *SessionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// GetGlobalCookiesRequest asks the master for a snapshot of the Global Cookie
// Jar.
type GetGlobalCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalCookiesRequest) Reset() {
	*x = GetGlobalCookiesRequest{}
	mi := &file_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalCookiesRequest) ProtoMessage() {}

func (x *GetGlobalCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalCookiesRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalCookiesRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{6}
}

func (x *GetGlobalCookiesRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

// GetGlobalCookiesResponse carries the current cookie jar snapshot.
// It is also used as the payload pushed over the WatchCookies stream.
type GetGlobalCookiesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Cookies []*Cookie              `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty"`
	// Monotonically increasing version so workers can detect stale snapshots.
	Version       int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalCookiesResponse) Reset() {
	*x = GetGlobalCookiesResponse{}
	mi := &file_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalCookiesResponse) ProtoMessage() {}

func (x *GetGlobalCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalCookiesResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalCookiesResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{7}
}

func (x *GetGlobalCookiesResponse) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *GetGlobalCookiesResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// WatchCookiesRequest subscribes the caller to cookie-update events.
type WatchCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCookiesRequest) Reset() {
	*x = WatchCookiesRequest{}
	mi := &file_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCookiesRequest) ProtoMessage() {}

func (x *WatchCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCookiesRequest.ProtoReflect.Descriptor instead.
func (*WatchCookiesRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{8}
}

func (x *WatchCookiesRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

// GetAllStatusRequest asks for a full snapshot of every tracked session.
type GetAllStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStatusRequest) Reset() {
	*x = GetAllStatusRequest{}
	mi := &file_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStatusRequest) ProtoMessage() {}

func (x *GetAllStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAllStatusRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{9}
}

type GetAllStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionStatus       `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStatusResponse) Reset() {
	*x = GetAllStatusResponse{}
	mi := &file_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStatusResponse) ProtoMessage() {}

func (x *GetAllStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAllStatusResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllStatusResponse) GetSessions() []*SessionStatus {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\x02pb\"\xb6\x01\n" +
	"\x06Cookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12!\n" +
	"\fexpires_unix\x18\x05 \x01(\x03R\vexpiresUnix\x12\x16\n" +
	"\x06secure\x18\x06 \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\a \x01(\bR\bhttpOnly\"|\n" +
	"\rSessionStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\x12\x13\n" +
	"\x05pc_id\x18\x02 \x01(\tR\x04pcId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12!\n" +
	"\fcookie_value\x18\x04 \x01(\tR\vcookieValue\"r\n" +
	"\x16BroadcastCookieRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x05R\tsessionId\x12$\n" +
	"\acookies\x18\x03 \x03(\v2\n" +
	".pb.CookieR\acookies\"5\n" +
	"\x17BroadcastCookieResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"@\n" +
	"\x13UpdateStatusRequest\x12)\n" +
	"\x06status\x18\x01 \x01(\v2\x11.pb.SessionStatusR\x06status\"&\n" +
	"\x14UpdateStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\".\n" +
	"\x17GetGlobalCookiesRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\"Z\n" +
	"\x18GetGlobalCookiesResponse\x12$\n" +
	"\acookies\x18\x01 \x03(\v2\n" +
	".pb.CookieR\acookies\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"*\n" +
	"\x13WatchCookiesRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\"\x15\n" +
	"\x13GetAllStatusRequest\"E\n" +
	"\x14GetAllStatusResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.pb.SessionStatusR\bsessions2\xfc\x02\n" +
	"\x10MasterController\x12J\n" +
	"\x0fBroadcastCookie\x12\x1a.pb.BroadcastCookieRequest\x1a\x1b.pb.BroadcastCookieResponse\x12A\n" +
	"\fUpdateStatus\x12\x17.pb.UpdateStatusRequest\x1a\x18.pb.UpdateStatusResponse\x12M\n" +
	"\x10GetGlobalCookies\x12\x1b.pb.GetGlobalCookiesRequest\x1a\x1c.pb.GetGlobalCookiesResponse\x12G\n" +
	"\fWatchCookies\x12\x17.pb.WatchCookiesRequest\x1a\x1c.pb.GetGlobalCookiesResponse0\x01\x12A\n" +
	"\fGetAllStatus\x12\x17.pb.GetAllStatusRequest\x1a\x18.pb.GetAllStatusResponseB0Z.github.com/firasghr/GoSessionEngine/cluster/pbb\x06proto3"

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData []byte
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)))
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_controller_proto_goTypes = []any{
	(*Cookie)(nil),                   // 0: pb.Cookie
	(*SessionStatus)(nil),            // 1: pb.SessionStatus
	(*BroadcastCookieRequest)(nil),   // 2: pb.BroadcastCookieRequest
	(*BroadcastCookieResponse)(nil),  // 3: pb.BroadcastCookieResponse
	(*UpdateStatusRequest)(nil),      // 4: pb.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),     // 5: pb.UpdateStatusResponse
	(*GetGlobalCookiesRequest)(nil),  // 6: pb.GetGlobalCookiesRequest
	(*GetGlobalCookiesResponse)(nil), // 7: pb.GetGlobalCookiesResponse
	(*WatchCookiesRequest)(nil),      // 8: pb.WatchCookiesRequest
	(*GetAllStatusRequest)(nil),      // 9: pb.GetAllStatusRequest
	(*GetAllStatusResponse)(nil),     // 10: pb.GetAllStatusResponse
}
var file_controller_proto_depIdxs = []int32{
	0,  // 0: pb.BroadcastCookieRequest.cookies:type_name -> pb.Cookie
	1,  // 1: pb.UpdateStatusRequest.status:type_name -> pb.SessionStatus
	0,  // 2: pb.GetGlobalCookiesResponse.cookies:type_name -> pb.Cookie
	1,  // 3: pb.GetAllStatusResponse.sessions:type_name -> pb.SessionStatus
	2,  // 4: pb.MasterController.BroadcastCookie:input_type -> pb.BroadcastCookieRequest
	4,  // 5: pb.MasterController.UpdateStatus:input_type -> pb.UpdateStatusRequest
	6,  // 6: pb.MasterController.GetGlobalCookies:input_type -> pb.GetGlobalCookiesRequest
	8,  // 7: pb.MasterController.WatchCookies:input_type -> pb.WatchCookiesRequest
	9,  // 8: pb.MasterController.GetAllStatus:input_type -> pb.GetAllStatusRequest
	3,  // 9: pb.MasterController.BroadcastCookie:output_type -> pb.BroadcastCookieResponse
	5,  // 10: pb.MasterController.UpdateStatus:output_type -> pb.UpdateStatusResponse
	7,  // 11: pb.MasterController.GetGlobalCookies:output_type -> pb.GetGlobalCookiesResponse
	7,  // 12: pb.MasterController.WatchCookies:output_type -> pb.GetGlobalCookiesResponse
	10, // 13: pb.MasterController.GetAllStatus:output_type -> pb.GetAllStatusResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
