// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: controller.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterController_BroadcastCookie_FullMethodName  = "/pb.MasterController/BroadcastCookie"
	MasterController_UpdateStatus_FullMethodName     = "/pb.MasterController/UpdateStatus"
	MasterController_GetGlobalCookies_FullMethodName = "/pb.MasterController/GetGlobalCookies"
	MasterController_WatchCookies_FullMethodName     = "/pb.MasterController/WatchCookies"
	MasterController_GetAllStatus_FullMethodName     = "/pb.MasterController/GetAllStatus"
)

// MasterControllerClient is the client API for MasterController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MasterController is the central coordinator for a 6-PC, 2 000-session
// GoSessionEngine cluster.
//
// Responsibilities:
//  1. Maintain a Global Cookie Jar: when any worker solves a JS/bot challenge
//     it calls BroadcastCookie; the master persists the cookies and fans them
//     out to all active WatchCookies subscribers so other workers can begin
//     making authenticated requests immediately.
//  2. Track session states: workers call UpdateStatus whenever a session
//     transitions between lifecycle states.  GetAllStatus lets operators
//     and monitoring tools inspect the entire cluster in one RPC.
type MasterControllerClient interface {
	// BroadcastCookie is called by a worker that has obtained valid session
	// cookies (e.g. after solving a Cloudflare / Akamai JS challenge).
	// The master stores the cookies and pushes them to all WatchCookies
	// subscribers.
	BroadcastCookie(ctx context.Context, in *BroadcastCookieRequest, opts ...grpc.CallOption) (*BroadcastCookieResponse, error)
	// UpdateStatus reports the current lifecycle state of a single session.
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error)
	// GetGlobalCookies returns a snapshot of the current Global Cookie Jar.
	GetGlobalCookies(ctx context.Context, in *GetGlobalCookiesRequest, opts ...grpc.CallOption) (*GetGlobalCookiesResponse, error)
	// WatchCookies opens a server-streaming RPC.  The master pushes a new
	// GetGlobalCookiesResponse every time BroadcastCookie adds fresh cookies,
	// so subscribers receive updates with minimal latency.
	WatchCookies(ctx context.Context, in *WatchCookiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetGlobalCookiesResponse], error)
	// GetAllStatus returns a snapshot of every tracked session across all PCs.
	GetAllStatus(ctx context.Context, in *GetAllStatusRequest, opts ...grpc.CallOption) (*GetAllStatusResponse, error)
}

type masterControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterControllerClient(cc grpc.ClientConnInterface) MasterControllerClient {
	return &masterControllerClient{cc}
}

func (c *masterControllerClient) BroadcastCookie(ctx context.Context, in *BroadcastCookieRequest, opts ...grpc.CallOption) (*BroadcastCookieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastCookieResponse)
	err := c.cc.Invoke(ctx, MasterController_BroadcastCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterControllerClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatusResponse)
	err := c.cc.Invoke(ctx, MasterController_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterControllerClient) GetGlobalCookies(ctx context.Context, in *GetGlobalCookiesRequest, opts ...grpc.CallOption) (*GetGlobalCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalCookiesResponse)
	err := c.cc.Invoke(ctx, MasterController_GetGlobalCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterControllerClient) WatchCookies(ctx context.Context, in *WatchCookiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetGlobalCookiesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MasterController_ServiceDesc.Streams[0], MasterController_WatchCookies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchCookiesRequest, GetGlobalCookiesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterController_WatchCookiesClient = grpc.ServerStreamingClient[GetGlobalCookiesResponse]

func (c *masterControllerClient) GetAllStatus(ctx context.Context, in *GetAllStatusRequest, opts ...grpc.CallOption) (*GetAllStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllStatusResponse)
	err := c.cc.Invoke(ctx, MasterController_GetAllStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterControllerServer is the server API for MasterController service.
// All implementations must embed UnimplementedMasterControllerServer
// for forward compatibility.
//
// MasterController is the central coordinator for a 6-PC, 2 000-session
// GoSessionEngine cluster.
//
// Responsibilities:
//  1. Maintain a Global Cookie Jar: when any worker solves a JS/bot challenge
//     it calls BroadcastCookie; the master persists the cookies and fans them
//     out to all active WatchCookies subscribers so other workers can begin
//     making authenticated requests immediately.
//  2. Track session states: workers call UpdateStatus whenever a session
//     transitions between lifecycle states.  GetAllStatus lets operators
//     and monitoring tools inspect the entire cluster in one RPC.
type MasterControllerServer interface {
	// BroadcastCookie is called by a worker that has obtained valid session
	// cookies (e.g. after solving a Cloudflare / Akamai JS challenge).
	// The master stores the cookies and pushes them to all WatchCookies
	// subscribers.
	BroadcastCookie(context.Context, *BroadcastCookieRequest) (*BroadcastCookieResponse, error)
	// UpdateStatus reports the current lifecycle state of a single session.
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error)
	// GetGlobalCookies returns a snapshot of the current Global Cookie Jar.
	GetGlobalCookies(context.Context, *GetGlobalCookiesRequest) (*GetGlobalCookiesResponse, error)
	// WatchCookies opens a server-streaming RPC.  The master pushes a new
	// GetGlobalCookiesResponse every time BroadcastCookie adds fresh cookies,
	// so subscribers receive updates with minimal latency.
	WatchCookies(*WatchCookiesRequest, grpc.ServerStreamingServer[GetGlobalCookiesResponse]) error
	// GetAllStatus returns a snapshot of every tracked session across all PCs.
	GetAllStatus(context.Context, *GetAllStatusRequest) (*GetAllStatusResponse, error)
	mustEmbedUnimplementedMasterControllerServer()
}

// UnimplementedMasterControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterControllerServer struct{}

func (UnimplementedMasterControllerServer) BroadcastCookie(context.Context, *BroadcastCookieRequest) (*BroadcastCookieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastCookie not implemented")
}
func (UnimplementedMasterControllerServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedMasterControllerServer) GetGlobalCookies(context.Context, *GetGlobalCookiesRequest) (*GetGlobalCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalCookies not implemented")
}
func (UnimplementedMasterControllerServer) WatchCookies(*WatchCookiesRequest, grpc.ServerStreamingServer[GetGlobalCookiesResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchCookies not implemented")
}
func (UnimplementedMasterControllerServer) GetAllStatus(context.Context, *GetAllStatusRequest) (*GetAllStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllStatus not implemented")
}
func (UnimplementedMasterControllerServer) mustEmbedUnimplementedMasterControllerServer() {}
func (UnimplementedMasterControllerServer) testEmbeddedByValue()                          {}

// UnsafeMasterControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterControllerServer will
// result in compilation errors.
type UnsafeMasterControllerServer interface {
	mustEmbedUnimplementedMasterControllerServer()
}

func RegisterMasterControllerServer(s grpc.ServiceRegistrar, srv MasterControllerServer) {
	// If the following call panics, it indicates UnimplementedMasterControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterController_ServiceDesc, srv)
}

func _MasterController_BroadcastCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControllerServer).BroadcastCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterController_BroadcastCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControllerServer).BroadcastCookie(ctx, req.(*BroadcastCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterController_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControllerServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterController_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControllerServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterController_GetGlobalCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControllerServer).GetGlobalCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterController_GetGlobalCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControllerServer).GetGlobalCookies(ctx, req.(*GetGlobalCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterController_WatchCookies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCookiesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MasterControllerServer).WatchCookies(m, &grpc.GenericServerStream[WatchCookiesRequest, GetGlobalCookiesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterController_WatchCookiesServer = grpc.ServerStreamingServer[GetGlobalCookiesResponse]

func _MasterController_GetAllStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControllerServer).GetAllStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterController_GetAllStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControllerServer).GetAllStatus(ctx, req.(*GetAllStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterController_ServiceDesc is the grpc.ServiceDesc for MasterController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MasterController",
	HandlerType: (*MasterControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastCookie",
			Handler:    _MasterController_BroadcastCookie_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _MasterController_UpdateStatus_Handler,
		},
		{
			MethodName: "GetGlobalCookies",
			Handler:    _MasterController_GetGlobalCookies_Handler,
		},
		{
			MethodName: "GetAllStatus",
			Handler:    _MasterController_GetAllStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCookies",
			Handler:       _MasterController_WatchCookies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}
